object Versions {
    const val FIREBASE_ANALYTICS: String = "17.5.0"
    const val GOOGLE_SERVICE = "4.3.3"
    const val ANDROID_JUNIT_JACOCO_PLUGIN: String = "0.16.0"
    const val ANDROIDX_PAGING: String = "2.1.2"
    const val MP_ANDROID_CHART = "3.1.0"
    const val DATABASE_SQL_CIPHER = "4.4.0"
    const val MOCKWEBSERVER: String = "4.7.2"
    const val RETROFIT = "2.9.0"
    const val TIMBER = "4.7.1"
    const val KOIN = "2.2.0-alpha-1"
    const val PHILOLOGY = "2.1.0"
    const val RXJAVA2_RXANDROID = "2.0.2"
    const val RXJAVA2_RXJAVA = "2.2.2"
    const val BARISTA = "3.5.0"
    const val FRAGMENT_TESTING = "1.2.5"
    const val ROBOLECTRIC = "4.3.1"
    const val OKHTTP = "4.7.2"
    const val SCARLET = "0.1.10"
    const val MOCKK = "1.9.3"
    const val JUNIT5_VINTAGE = "5.3.2"
    const val JUNIT5 = "5.4.1"
    const val COROUTINES = "1.3.8"
    const val MOSHI = "1.8.0"

    const val MIN_ANDROID_SDK = 21
    const val TARGET_ANDROID_SDK = 29

    const val GRADLE = "4.0.0"
    const val KOTLIN = "1.4.0"
    const val ANDROIDX_CORE_KTX = "1.1.0"
    const val ANDROIDX_APPCOMPAT = "1.1.0"
    const val ANDROID_MATERIAL = "1.1.0"
    const val ANDROIDX_CONSTRAINTLAYOUT = "2.0.1"
    const val ANDROIDX_NAVIGATION = "2.3.0"
    const val ANDROIDX_LIFECYCLE = "2.2.0"
    const val ANDROIDX_LEGACY_SUPPORT = "1.0.0"
    const val ANDROIDX_VECTOR_DRAWABLE = "1.0.1"
    const val JUNIT = "4.12"
    const val ANDROIDX_TEST_EXTENSION_JUNIT = "1.1.1"
    const val ANDROIDX_TEST_ESPRESSO_CORE = "3.2.0"
    const val ANDROIDX_MULTIDEX = "2.0.1"
    const val CALLIGRAPHY = "3.1.1"
    const val VIEWPUMP = "2.0.3"
    const val ANDROIDX_ROOM = "2.2.5"
    const val BUGSNAG_PLUGIN = "4.7.5"
    const val BUGSNAG_ANDROID = "5.0.2"
}